/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.jskat

import kotlin.test.Test
import kotlin.test.assertNotNull

class JSkatTest {
    @Test fun testAppHasAGreeting() {
        val classUnderTest = JSkat()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }
}
